<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CaseObject Manager</name>
   <tag></tag>
   <elementGuidId>a9e8dc55-6270-4340-adb7-a5873cfb65c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='oneHeader']/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/ul/li[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lookup__item SETUP_NODE slds-text-link--reset slds-grid slds-grid--vertical-align-center slds-truncate default highlighted uiAutocompleteOption forceSearchInputDesktopOption</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>3835:0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>uiAutocompleteOption forceSearchInputDesktopOption</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactive-uid</name>
      <type>Main</type>
      <value>63</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CaseObject Manager</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneHeader&quot;)/div[@class=&quot;slds-global-header slds-grid slds-grid--align-spread&quot;]/div[@class=&quot;slds-global-header__item slds-global-header__item--search&quot;]/div[@class=&quot;slds-grid slds-nowrap slds-text-body--regular slds-text-color--weak slds-is-relative forceSearchInputDesktop onesetupSetupSearchInputDesktop focused&quot;]/div[@class=&quot;contentWrapper slds-size--1-of-1 slds-nowrap slds-border_top slds-border_left slds-border_right slds-border_bottom slds-grid slds-grid--vertical-align-center slds-scrollable_none focused&quot;]/div[@class=&quot;inputWrapper slds-grid slds-grid--align-center slds-grid--vertical-align-center slds-size--1-of-1&quot;]/div[@class=&quot;autocompleteWrapper slds-grow slds-form-element__control&quot;]/div[@class=&quot;uiInput uiAutocomplete uiInput--default&quot;]/div[@class=&quot;list slds-size--1-of-1 slds-show slds-p-vertical--xx-small lookup__menu uiAbstractList uiAutocompleteList&quot;]/div[@class=&quot;listContent&quot;]/ul[@class=&quot;lookup__list  visible&quot;]/li[@class=&quot;lookup__item SETUP_NODE slds-text-link--reset slds-grid slds-grid--vertical-align-center slds-truncate default highlighted uiAutocompleteOption forceSearchInputDesktopOption&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//header[@id='oneHeader']/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/ul/li[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casey Ruess'])[1]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//li[8]</value>
   </webElementXpaths>
</WebElementEntity>
