<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Settings_Setup</name>
   <tag></tag>
   <elementGuidId>72637823-6a4f-429f-9a9d-f6e189f0a9a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-aura-class=&quot;uiTooltip&quot;])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-aura-class=&quot;uiTooltip&quot;])[4]</value>
   </webElementProperties>
</WebElementEntity>
