<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DD_AccountandprotocolAssignments</name>
   <tag></tag>
   <elementGuidId>5652dafd-02c5-4899-8ea9-871096e2163b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='tab___01r41000001Yf8X']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='tab___01r41000001Yf8X']</value>
   </webElementProperties>
</WebElementEntity>
