<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_Setup</name>
   <tag></tag>
   <elementGuidId>5c4b1280-c75b-405c-a445-6ff7b88ca513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='related_setup_app_home']/a/div/div/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='related_setup_app_home']/a/div/div/span/span[2]</value>
   </webElementProperties>
</WebElementEntity>
