<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit</name>
   <tag></tag>
   <elementGuidId>d6726ac5-13b6-4aa4-99bc-437ea66febb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='setupComponent']/div/div/div/section/div/div[2]/div/div/table/tbody/tr[12]/td[7]/div/div/div[2]/div/ul/li/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-col slds-size_10-of-12</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2804:0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_4&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@id=&quot;setupComponent&quot;]/div[@class=&quot;setupcontent&quot;]/div[@class=&quot;slds-card slds-grid object-detail-page&quot;]/div[@class=&quot;slds-grid slds-container--fluid slds-grid--vertical-stretch&quot;]/div[@class=&quot;slds-container--fluid object-manager-content-wrapper&quot;]/div[@class=&quot;object-manager-content-position-wrapper&quot;]/div[@id=&quot;setupComponent&quot;]/div[@class=&quot;setupcontent&quot;]/div[@class=&quot;object-container&quot;]/div[@class=&quot;object-content&quot;]/section[@class=&quot;related-list-card&quot;]/div[@class=&quot;related-list-card-content&quot;]/div[@class=&quot;scrollerWrapper&quot;]/div[@class=&quot;scroller uiScroller scroller-wrapper scroll-bidirectional native&quot;]/div[@class=&quot;scroller&quot;]/table[@class=&quot;slds-table slds-table-bordered uiVirtualDataGrid--default uiVirtualDataGrid&quot;]/tbody[1]/tr[12]/td[7]/div[@class=&quot;objectManagerVirtualActionMenu&quot;]/div[@class=&quot;uiMenu objectManagerActionsMenu&quot;]/div[@class=&quot;actionMenu popupTargetContainer uiPopupTarget uiMenuList uiMenuList--right uiMenuList--default visible positioned&quot;]/div[@class=&quot;actionMenu&quot;]/ul[@class=&quot;scrollable&quot;]/li[@class=&quot;slds-dropdown__item uiMenuItem onesetupSetupMenuItem&quot;]/a[1]/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-size_10-of-12&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='setupComponent']/div/div/div/section/div/div[2]/div/div/table/tbody/tr[12]/td[7]/div/div/div[2]/div/ul/li/a/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[12]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='False'])[12]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[4]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div/ul/li/a/div/div</value>
   </webElementXpaths>
</WebElementEntity>
